name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


permissions:
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      # Because of scheduled runs, by default run on default branch
      with:
        path: workspace/clava-flow

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install node libraries
      working-directory: workspace/clava-flow
      run: npm install

    - name: Build clava-flow
      working-directory: workspace/clava-flow
      run: npm run build

    - name: Run clava-flow tests
      working-directory: workspace/clava-flow
      run: npm run test
